### PR TITLE
Update to compile/run in KSP 1.2.1.

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by miki-g** [comment]
HOooorayyyYyYyyy

**Comment by futuramaking** [comment]
Confirm work on 1.2.2
until this is fix is committed, thanks  Kerbas-ad-astra
just replace the .dll in KSCSwitcher\Plugins with the attached .dll.txt and remove .txt
[KSCSwitcher.dll.txt](https://github.com/KSP-RO/KSCSwitcher/files/746882/KSCSwitcher.dll.txt)

**Review by futuramaking — COMMENTED** [review]
confirmed work on 1.2.2 with RSS on windows 10

**Comment by rsparkyc** [comment]
There's actually an open PR on what this was forked from:
https://github.com/jbengtson/KSCSwitcher/pull/4

**Comment by rsparkyc** [comment]
This is the same changes that have been applied in the other PR, so merging this won't really hurt anything.

**Pull request merged**
